# homepage:
#     path: /
#     defaults: 
#         _controller: FrameworkBundle:Redirect:urlRedirect
#         path: /accueil
#         permanent: true


# # FOR DEBUG PAGE:
# site_buildpagedetails:
#     path:      /details/{slug}
#     defaults:
#         _controller: BuilderPageBundle:Builder\BuildPage:buildPageDetails





# site_buildpageid:
#     path:      /{slug}/{id}
#     defaults:
#         _controller: BuilderPageBundle:Builder\BuildPage:buildPage


# #MAIN ROUTE ALL MATCH:
# site_buildpage:
#     path:      /{slug}/
#     defaults:  { _controller: BuilderPageBundle:Builder\BuildPage:buildPage, slug: "accueil" }
#     # requirements:
#     #     slug: .+